language: python
python:
    - "2.7"
install: pip install -r requirements.txt
env:
    - CONFIG_PATH=blog.config.TravisConfig
before_script:
    - psql -c 'create database "blogful-test";' -U postgres
script:
    - cd tests
    - python test_filter.py
    - python test_views_integration.py
    - python test_views_acceptance.py
