"""empty message

Revision ID: 3a3b4c4c7b19
Revises: 4349382f8662
Create Date: 2015-04-07 21:07:30.908522

"""

# revision identifiers, used by Alembic.
revision = '3a3b4c4c7b19'
down_revision = '4349382f8662'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
