"""empty message

Revision ID: 4349382f8662
Revises: None
Create Date: 2015-04-07 20:36:01.110510

"""

# revision identifiers, used by Alembic.
revision = '4349382f8662'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
